var sporen = [
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "AC",
    namen: { lang: "Abcoude", kort: "Abcoude", middel: "Abcoude" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400047",
    lat: 52.2785,
    lng: 4.977,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400047"
  },
  {
    sporen: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object]
    ],
    synoniemen: ["Arnhem"],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "AH",
    namen: { lang: "Arnhem Centraal", kort: "Arnhem C", middel: "Arnhem C." },
    stationType: "KNOOPPUNT_INTERCITY_STATION",
    land: "NL",
    UICCode: "8400071",
    lat: 51.9850006103516,
    lng: 5.89916658401489,
    radius: 525,
    naderenRadius: 1200,
    EVACode: "8400071"
  },
  {
    sporen: [],
    synoniemen: ["Aken"],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "AHBF",
    namen: { lang: "Aachen Hbf", kort: "Aachen", middel: "Aachen Hbf" },
    stationType: "KNOOPPUNT_INTERCITY_STATION",
    land: "D",
    UICCode: "8015345",
    lat: 50.7678,
    lng: 6.091499,
    radius: 1,
    naderenRadius: 1,
    EVACode: "8000001"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "AHP",
    namen: {
      lang: "Arnhem Velperpoort",
      kort: "Velperprt",
      middel: "Velperpoort"
    },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400072",
    lat: 51.985279083252,
    lng: 5.91944456100464,
    radius: 400,
    naderenRadius: 1200,
    EVACode: "8400072"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "AHPR",
    namen: {
      lang: "Arnhem Presikhaaf",
      kort: "Presikhaaf",
      middel: "Presikhaaf"
    },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400075",
    lat: 51.9880561828613,
    lng: 5.94388866424561,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400075"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "AHZ",
    namen: { lang: "Arnhem Zuid", kort: "Arnhem Z", middel: "Arnhem Zuid" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400227",
    lat: 51.9550018310547,
    lng: 5.85194444656372,
    radius: 200,
    naderenRadius: 1600,
    EVACode: "8400029"
  },
  {
    sporen: [],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "AIME",
    namen: {
      lang: "Aime-la-Plagne",
      kort: "Aime-la-Pl",
      middel: "Aime-la-Plagne"
    },
    stationType: "INTERCITY_STATION",
    land: "F",
    UICCode: "8774176",
    lat: 45.55438,
    lng: 6.64869,
    radius: 1,
    naderenRadius: 1,
    EVACode: "8700431"
  },
  {
    sporen: [],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "AIXTGV",
    namen: {
      lang: "Aix-en-Provence TGV",
      kort: "Aix-en-Pro",
      middel: "Aix-en-Provence"
    },
    stationType: "INTERCITY_STATION",
    land: "F",
    UICCode: "8731901",
    lat: 43.5228190773429,
    lng: 5.44531345367431,
    radius: 1,
    naderenRadius: 1,
    EVACode: "8704980"
  },
  {
    sporen: [[Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "AKL",
    namen: { lang: "Arkel", kort: "Arkel", middel: "Arkel" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400068",
    lat: 51.8719444274902,
    lng: 4.99277782440186,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400068"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "AKM",
    namen: { lang: "Akkrum", kort: "Akkrum", middel: "Akkrum" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400049",
    lat: 53.0463905334473,
    lng: 5.84361124038696,
    radius: 200,
    naderenRadius: 1600,
    EVACode: "8400049"
  },
  {
    sporen: [],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "ALBERT",
    namen: { lang: "Albertville", kort: "Albertv.", middel: "Albertville" },
    stationType: "INTERCITY_STATION",
    land: "F",
    UICCode: "8774164",
    lat: 45.67302,
    lng: 6.38306,
    radius: 1,
    naderenRadius: 1,
    EVACode: "8700128"
  },
  {
    sporen: [[Object], [Object], [Object], [Object]],
    synoniemen: ["Almere"],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "ALM",
    namen: { lang: "Almere Centrum", kort: "Almere C", middel: "Almere C." },
    stationType: "KNOOPPUNT_INTERCITY_STATION",
    land: "NL",
    UICCode: "8400080",
    lat: 52.37503,
    lng: 5.21764,
    radius: 525,
    naderenRadius: 1200,
    EVACode: "8400080"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "ALMB",
    namen: { lang: "Almere Buiten", kort: "Buiten", middel: "Buiten" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400081",
    lat: 52.3941650390625,
    lng: 5.2780556678772,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400081"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "ALMM",
    namen: {
      lang: "Almere Muziekwijk",
      kort: "Muziekwijk",
      middel: "Muziekwijk"
    },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400082",
    lat: 52.3675003051758,
    lng: 5.19027757644653,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400082"
  },
  {
    sporen: [[Object], [Object], [Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "ALMO",
    namen: {
      lang: "Almere Oostvaarders",
      kort: "Oostvaard",
      middel: "Oostvaarders"
    },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400226",
    lat: 52.4033317565918,
    lng: 5.30055570602417,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400024"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "ALMP",
    namen: { lang: "Almere Parkwijk", kort: "Parkwijk", middel: "Parkwijk" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400104",
    lat: 52.3766670227051,
    lng: 5.24472236633301,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8479008"
  },
  {
    sporen: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object]
    ],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "AMF",
    namen: { lang: "Amersfoort", kort: "Amersfoort", middel: "Amersfoort" },
    stationType: "KNOOPPUNT_INTERCITY_STATION",
    land: "NL",
    UICCode: "8400055",
    lat: 52.1538887023926,
    lng: 5.37055540084839,
    radius: 525,
    naderenRadius: 1200,
    EVACode: "8400055"
  },
  {
    sporen: [[Object], [Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "AMFS",
    namen: {
      lang: "Amersfoort Schothorst",
      kort: "Schothorst",
      middel: "Schothorst"
    },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400054",
    lat: 52.1748221374512,
    lng: 5.40388870239258,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400054"
  },
  {
    sporen: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object]
    ],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "AML",
    namen: { lang: "Almelo", kort: "Almelo", middel: "Almelo" },
    stationType: "KNOOPPUNT_INTERCITY_STATION",
    land: "NL",
    UICCode: "8400051",
    lat: 52.3580551147461,
    lng: 6.65388870239258,
    radius: 525,
    naderenRadius: 1200,
    EVACode: "8400051"
  },
  {
    sporen: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object]
    ],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "AMR",
    namen: { lang: "Alkmaar", kort: "Alkmaar", middel: "Alkmaar" },
    stationType: "KNOOPPUNT_INTERCITY_STATION",
    land: "NL",
    UICCode: "8400050",
    lat: 52.6377792358398,
    lng: 4.73972225189209,
    radius: 525,
    naderenRadius: 1200,
    EVACode: "8400050"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "AMRI",
    namen: { lang: "Almelo de Riet", kort: "de Riet", middel: "de Riet" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400520",
    lat: 52.3419456481934,
    lng: 6.66666650772095,
    radius: 200,
    naderenRadius: 1600,
    EVACode: "8400520"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "AMRN",
    namen: { lang: "Alkmaar Noord", kort: "Alkmaar N", middel: "Alkmaar N." },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400052",
    lat: 52.6438903808594,
    lng: 4.76416683197022,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400052"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "ANA",
    namen: {
      lang: "Anna Paulowna",
      kort: "Anna Paulo",
      middel: "Anna Paulowna"
    },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400065",
    lat: 52.8672218322754,
    lng: 4.81111097335815,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400065"
  },
  {
    sporen: [],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "ANDD",
    namen: {
      lang: "Antwerpen-Noorderdokken",
      kort: "Antw-dok",
      middel: "Antw-N'dokken"
    },
    stationType: "STOPTREIN_STATION",
    land: "B",
    UICCode: "8821089",
    lat: 51.261686,
    lng: 4.4274315,
    radius: 1,
    naderenRadius: 1,
    EVACode: "8800188"
  },
  {
    sporen: [[Object], [Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "APD",
    namen: { lang: "Apeldoorn", kort: "Apeldoorn", middel: "Apeldoorn" },
    stationType: "KNOOPPUNT_INTERCITY_STATION",
    land: "NL",
    UICCode: "8400066",
    lat: 52.2091674804687,
    lng: 5.97027778625488,
    radius: 525,
    naderenRadius: 1200,
    EVACode: "8400066"
  },
  {
    sporen: [[Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "APDM",
    namen: { lang: "Apeldoorn De Maten", kort: "De Maten", middel: "De Maten" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400233",
    lat: 52.2052764892578,
    lng: 6.00055551528931,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400032"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "APDO",
    namen: { lang: "Apeldoorn Osseveld", kort: "Osseveld", middel: "Osseveld" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400229",
    lat: 52.2152786254883,
    lng: 6.00444459915161,
    radius: 200,
    naderenRadius: 1600,
    EVACode: "8400033"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "APG",
    namen: { lang: "Appingedam", kort: "Appingedam", middel: "Appingedam" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400067",
    lat: 53.3258135,
    lng: 6.8619577,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400067"
  },
  {
    sporen: [[Object], [Object], [Object]],
    synoniemen: ["Alphen aan den Rijn"],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "APN",
    namen: {
      lang: "Alphen a/d Rijn",
      kort: "Alphen",
      middel: "Alphen a/d Rijn"
    },
    stationType: "KNOOPPUNT_INTERCITY_STATION",
    land: "NL",
    UICCode: "8400053",
    lat: 52.1244430541992,
    lng: 4.65777778625488,
    radius: 525,
    naderenRadius: 1200,
    EVACode: "8400053"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "ARN",
    namen: { lang: "Arnemuiden", kort: "Arnemuiden", middel: "Arnemuiden" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400069",
    lat: 51.5016670227051,
    lng: 3.66916656494141,
    radius: 250,
    naderenRadius: 1200,
    EVACode: "8400069"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "ASA",
    namen: { lang: "Amsterdam Amstel", kort: "Amstel", middel: "Amstel" },
    stationType: "INTERCITY_STATION",
    land: "NL",
    UICCode: "8400057",
    lat: 52.3466682434082,
    lng: 4.91777801513672,
    radius: 260,
    naderenRadius: 1200,
    EVACode: "8400057"
  },
  {
    sporen: [[Object], [Object], [Object], [Object], [Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "ASB",
    namen: {
      lang: "Amsterdam Bijlmer ArenA",
      kort: "Bijlmer A",
      middel: "Bijlmer ArenA"
    },
    stationType: "KNOOPPUNT_STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400074",
    lat: 52.3122215270996,
    lng: 4.94694423675537,
    radius: 260,
    naderenRadius: 1200,
    EVACode: "8400074"
  },
  {
    sporen: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object]
    ],
    synoniemen: ["Amsterdam"],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "ASD",
    namen: {
      lang: "Amsterdam Centraal",
      kort: "Amsterdam",
      middel: "Amsterdam C."
    },
    stationType: "MEGA_STATION",
    land: "NL",
    UICCode: "8400058",
    lat: 52.3788871765137,
    lng: 4.90027761459351,
    radius: 525,
    naderenRadius: 1200,
    EVACode: "8400058"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "ASDL",
    namen: { lang: "Amsterdam Lelylaan", kort: "Lelylaan", middel: "Lelylaan" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400079",
    lat: 52.3577766418457,
    lng: 4.83388900756836,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400079"
  },
  {
    sporen: [[Object], [Object], [Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "ASDM",
    namen: {
      lang: "Amsterdam Muiderpoort",
      kort: "Muiderprt",
      middel: "Muiderpoort"
    },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400060",
    lat: 52.3605537414551,
    lng: 4.93111133575439,
    radius: 260,
    naderenRadius: 800,
    EVACode: "8400060"
  },
  {
    sporen: [[Object], [Object], [Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "ASDZ",
    namen: {
      lang: "Amsterdam Zuid",
      kort: "Amsterdm Z",
      middel: "Amsterdam Z."
    },
    stationType: "INTERCITY_STATION",
    land: "NL",
    UICCode: "8400061",
    lat: 52.338889,
    lng: 4.872356,
    radius: 260,
    naderenRadius: 1200,
    EVACode: "8400061"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "ASHD",
    namen: {
      lang: "Amsterdam Holendrecht",
      kort: "Holendrcht",
      middel: "Holendrecht"
    },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400231",
    lat: 52.29844,
    lng: 4.95972,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400076"
  },
  {
    sporen: [[Object], [Object], [Object], [Object], [Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "ASN",
    namen: { lang: "Assen", kort: "Assen", middel: "Assen" },
    stationType: "KNOOPPUNT_INTERCITY_STATION",
    land: "NL",
    UICCode: "8400073",
    lat: 52.9916648864746,
    lng: 6.57083320617676,
    radius: 300,
    naderenRadius: 1600,
    EVACode: "8400073"
  },
  {
    sporen: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object]
    ],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "ASS",
    namen: {
      lang: "Amsterdam Sloterdijk",
      kort: "Sloterdijk",
      middel: "Sloterdijk"
    },
    stationType: "KNOOPPUNT_INTERCITY_STATION",
    land: "NL",
    UICCode: "8400059",
    lat: 52.3888893127441,
    lng: 4.83777761459351,
    radius: 525,
    naderenRadius: 1200,
    EVACode: "8400059"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "ASSP",
    namen: {
      lang: "Amsterdam Science Park",
      kort: "Scienceprk",
      middel: "Science Park"
    },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400235",
    lat: 52.35526,
    lng: 4.94651,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400083"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "ATN",
    namen: { lang: "Aalten", kort: "Aalten", middel: "Aalten" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400045",
    lat: 51.9213265245505,
    lng: 6.57862722873687,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400045"
  },
  {
    sporen: [],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "ATW",
    namen: {
      lang: "Antwerpen-Centraal",
      kort: "Antwerpen",
      middel: "Antwerpen-C."
    },
    stationType: "MEGA_STATION",
    land: "B",
    UICCode: "8821006",
    lat: 51.2161,
    lng: 4.42122,
    radius: 1,
    naderenRadius: 1,
    EVACode: "8800007"
  },
  {
    sporen: [],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "ATWLB",
    namen: {
      lang: "Antwerpen-Luchtbal",
      kort: "Antw-Bal",
      middel: "Antw-Luchtbal"
    },
    stationType: "STOPTREIN_STATION",
    land: "B",
    UICCode: "8821063",
    lat: 51.2449375,
    lng: 4.4251543,
    radius: 1,
    naderenRadius: 1,
    EVACode: "8800187"
  },
  {
    sporen: [[Object], [Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "AVAT",
    namen: {
      lang: "Amersfoort Vathorst",
      kort: "Vathorst",
      middel: "Vathorst"
    },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400228",
    lat: 52.1927795410156,
    lng: 5.43388891220093,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400031"
  },
  {
    sporen: [],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "AVTGV",
    namen: { lang: "Avignon TGV", kort: "Avignon", middel: "Avignon TGV" },
    stationType: "MEGA_STATION",
    land: "F",
    UICCode: "8731896",
    lat: 43.92194,
    lng: 4.78604,
    radius: 1,
    naderenRadius: 1,
    EVACode: "8704918"
  },
  {
    sporen: [],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "AW",
    namen: { lang: "Aachen West", kort: "Aachen W", middel: "Aachen West" },
    stationType: "STOPTREIN_STATION",
    land: "D",
    UICCode: "8015199",
    lat: 50.78036,
    lng: 6.070715,
    radius: 1,
    naderenRadius: 1,
    EVACode: "8000404"
  },
  {
    sporen: [],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BADENZ",
    namen: { lang: "Baden (CH)", kort: "Baden (CH)", middel: "Baden (CH)" },
    stationType: "STOPTREIN_STATION",
    land: "CH",
    UICCode: "8503504",
    lat: 47.47638,
    lng: 8.30772,
    radius: 1,
    naderenRadius: 1,
    EVACode: "8503504"
  },
  {
    sporen: [],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BASELB",
    namen: { lang: "Basel Bad Bf", kort: "Basel Bad", middel: "Basel Bad Bf" },
    stationType: "STOPTREIN_STATION",
    land: "D",
    UICCode: "8014431",
    lat: 47.56815,
    lng: 7.6073,
    radius: 1,
    naderenRadius: 1,
    EVACode: "8000026"
  },
  {
    sporen: [],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BASELS",
    namen: { lang: "Basel SBB", kort: "Basel SBB", middel: "Basel SBB" },
    stationType: "MEGA_STATION",
    land: "CH",
    UICCode: "8500010",
    lat: 47.5474,
    lng: 7.58956,
    radius: 1,
    naderenRadius: 1,
    EVACode: "8500010"
  },
  {
    sporen: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object]
    ],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "BD",
    namen: { lang: "Breda", kort: "Breda", middel: "Breda" },
    stationType: "KNOOPPUNT_INTERCITY_STATION",
    land: "NL",
    UICCode: "8400131",
    lat: 51.5955543518066,
    lng: 4.78000020980835,
    radius: 525,
    naderenRadius: 1200,
    EVACode: "8400131"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "BDE",
    namen: { lang: "Bunde", kort: "Bunde", middel: "Bunde" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400140",
    lat: 50.8969459533691,
    lng: 5.73666667938232,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400140"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "BDG",
    namen: { lang: "Bodegraven", kort: "Bodegraven", middel: "Bodegraven" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400121",
    lat: 52.0813903808594,
    lng: 4.7461109161377,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400121"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "BDM",
    namen: { lang: "Bedum", kort: "Bedum", middel: "Bedum" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400094",
    lat: 53.3068857,
    lng: 6.593054,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400094"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BDPB",
    namen: {
      lang: "Breda-Prinsenbeek",
      kort: "Prinsenbk",
      middel: "Prinsenbeek"
    },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400132",
    lat: 51.606388092041,
    lng: 4.72083330154419,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400132"
  },
  {
    sporen: [],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BERCH",
    namen: {
      lang: "Antwerpen-Berchem",
      kort: "Antw-Berch",
      middel: "Antw-Berchem"
    },
    stationType: "KNOOPPUNT_STOPTREIN_STATION",
    land: "B",
    UICCode: "8821121",
    lat: 51.2001783,
    lng: 4.4327702,
    radius: 1,
    naderenRadius: 1,
    EVACode: "8800008"
  },
  {
    sporen: [[Object], [Object], [Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "BET",
    namen: { lang: "Best", kort: "Best", middel: "Best" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400112",
    lat: 51.5099983215332,
    lng: 5.38916683197022,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400112"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "BF",
    namen: { lang: "Baflo", kort: "Baflo", middel: "Baflo" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400089",
    lat: 53.3608969,
    lng: 6.5185581,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400089"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "BGN",
    namen: {
      lang: "Bergen op Zoom",
      kort: "Bergen opZ",
      middel: "Bergen op Zoom"
    },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400108",
    lat: 51.4938888549805,
    lng: 4.29611110687256,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400108"
  },
  {
    sporen: [],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BH",
    namen: { lang: "Bad Bentheim", kort: "Bentheim", middel: "Bad Bentheim" },
    stationType: "KNOOPPUNT_INTERCITY_STATION",
    land: "D",
    UICCode: "8021156",
    lat: 52.309685595156,
    lng: 7.15853691101074,
    radius: 1,
    naderenRadius: 1,
    EVACode: "8000879"
  },
  {
    sporen: [],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BHF",
    namen: {
      lang: "Berlin Ostbahnhof",
      kort: "Berlin Ost",
      middel: "Berlin Ostbhf"
    },
    stationType: "KNOOPPUNT_INTERCITY_STATION",
    land: "D",
    UICCode: "8003004",
    lat: 52.5104989,
    lng: 13.4346995,
    radius: 1,
    naderenRadius: 1,
    EVACode: "8010255"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "BHV",
    namen: { lang: "Bilthoven", kort: "Bilthoven", middel: "Bilthoven" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400114",
    lat: 52.1300010681152,
    lng: 5.20388889312744,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400114"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "BK",
    namen: { lang: "Beek-Elsloo", kort: "Beek-E", middel: "Beek-Elsloo" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400096",
    lat: 50.9474983215332,
    lng: 5.78666687011719,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400096"
  },
  {
    sporen: [[Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BKF",
    namen: {
      lang: "Bovenkarspel Flora",
      kort: "Bovenk Flo",
      middel: "Bovenkarspel Fl."
    },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400230",
    lat: 52.6961097717285,
    lng: 5.25277757644653,
    radius: 250,
    naderenRadius: 1200,
    EVACode: "8400230"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BKG",
    namen: {
      lang: "Bovenkarspel-Grootebroek",
      kort: "Bovenk-Gr",
      middel: "Bovenkarspel-Gr."
    },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400127",
    lat: 52.6949996948242,
    lng: 5.23777770996094,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400127"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BKL",
    namen: { lang: "Breukelen", kort: "Breukelen", middel: "Breukelen" },
    stationType: "KNOOPPUNT_STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400133",
    lat: 52.17149,
    lng: 4.9906,
    radius: 260,
    naderenRadius: 800,
    EVACode: "8400133"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "BL",
    namen: { lang: "Beilen", kort: "Beilen", middel: "Beilen" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400100",
    lat: 52.8547210693359,
    lng: 6.52111101150513,
    radius: 300,
    naderenRadius: 1600,
    EVACode: "8400100"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "BLL",
    namen: { lang: "Bloemendaal", kort: "Bloemendl", middel: "Bloemendaal" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400118",
    lat: 52.404167175293,
    lng: 4.62750005722046,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400118"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BMN",
    namen: { lang: "Brummen", kort: "Brummen", middel: "Brummen" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400136",
    lat: 52.0911102294922,
    lng: 6.14694452285767,
    radius: 200,
    naderenRadius: 1600,
    EVACode: "8400136"
  },
  {
    sporen: [[Object], [Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "BMR",
    namen: { lang: "Boxmeer", kort: "Boxmeer", middel: "Boxmeer" },
    stationType: "KNOOPPUNT_STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400128",
    lat: 51.6445217676531,
    lng: 5.93903303146362,
    radius: 525,
    naderenRadius: 1200,
    EVACode: "8400128"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BN",
    namen: { lang: "Borne", kort: "Borne", middel: "Borne" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400124",
    lat: 52.2988891601562,
    lng: 6.74805545806885,
    radius: 200,
    naderenRadius: 1600,
    EVACode: "8400124"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "BNC",
    namen: {
      lang: "Barneveld Centrum",
      kort: "Barnevld C",
      middel: "Barneveld C."
    },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400091",
    lat: 52.1399993896484,
    lng: 5.59027767181396,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400091"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BNK",
    namen: { lang: "Bunnik", kort: "Bunnik", middel: "Bunnik" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400141",
    lat: 52.0630569458008,
    lng: 5.19444465637207,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400141"
  },
  {
    sporen: [[Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BNN",
    namen: {
      lang: "Barneveld Noord",
      kort: "Barnevld N",
      middel: "Barneveld N."
    },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400092",
    lat: 52.1613883972168,
    lng: 5.59805536270142,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400092"
  },
  {
    sporen: [],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BONN",
    namen: { lang: "Bonn Hbf", kort: "Bonn Hbf", middel: "Bonn Hbf" },
    stationType: "STOPTREIN_STATION",
    land: "D",
    UICCode: "8015485",
    lat: 50.7320141646745,
    lng: 7.09712505340576,
    radius: 1,
    naderenRadius: 1,
    EVACode: "8000044"
  },
  {
    sporen: [],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BOURG",
    namen: {
      lang: "Bourg-St-Maurice",
      kort: "Bourg-StM",
      middel: "Bourg-St-Maurice"
    },
    stationType: "INTERCITY_STATION",
    land: "F",
    UICCode: "8774179",
    lat: 45.61918,
    lng: 6.77167,
    radius: 1,
    naderenRadius: 1,
    EVACode: "8700130"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: ["Bûtenpost"],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "BP",
    namen: { lang: "Buitenpost", kort: "Buitenpost", middel: "Buitenpost" },
    stationType: "KNOOPPUNT_SNELTREIN_STATION",
    land: "NL",
    UICCode: "8400139",
    lat: 53.2564547,
    lng: 6.1446496,
    radius: 525,
    naderenRadius: 1200,
    EVACode: "8400139"
  },
  {
    sporen: [[Object], [Object], [Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BR",
    namen: { lang: "Blerick", kort: "Blerick", middel: "Blerick" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400117",
    lat: 51.372501373291,
    lng: 6.15500020980835,
    radius: 525,
    naderenRadius: 1000,
    EVACode: "8400117"
  },
  {
    sporen: [[Object], [Object], [Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "BRD",
    namen: { lang: "Barendrecht", kort: "Barendrcht", middel: "Barendrecht" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400090",
    lat: 51.8547210693359,
    lng: 4.5533332824707,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400090"
  },
  {
    sporen: [],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BRESSX",
    namen: { lang: "Bressoux", kort: "Bressoux", middel: "Bressoux" },
    stationType: "STOPTREIN_STATION",
    land: "B",
    UICCode: "8843901",
    lat: 50.643829,
    lng: 5.6112542,
    radius: 1,
    naderenRadius: 1,
    EVACode: "8800107"
  },
  {
    sporen: [[Object], [Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "BRN",
    namen: { lang: "Baarn", kort: "Baarn", middel: "Baarn" },
    stationType: "KNOOPPUNT_STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400086",
    lat: 52.2083320617676,
    lng: 5.28083324432373,
    radius: 525,
    naderenRadius: 1200,
    EVACode: "8400086"
  },
  {
    sporen: [],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BRUSC",
    namen: {
      lang: "Brussel-Centraal",
      kort: "Brussel-C",
      middel: "Brussel-C."
    },
    stationType: "INTERCITY_STATION",
    land: "B",
    UICCode: "8813003",
    lat: 50.8454658,
    lng: 4.3571135,
    radius: 1,
    naderenRadius: 1,
    EVACode: "8800003"
  },
  {
    sporen: [],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BRUSN",
    namen: {
      lang: "Brussel-Noord",
      kort: "Brussel-N",
      middel: "Brussel-Noord"
    },
    stationType: "KNOOPPUNT_STOPTREIN_STATION",
    land: "B",
    UICCode: "8812005",
    lat: 50.8605262,
    lng: 4.3617873,
    radius: 1,
    naderenRadius: 1,
    EVACode: "8800002"
  },
  {
    sporen: [],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BRUSZ",
    namen: {
      lang: "Brussel-Zuid/Midi",
      kort: "Brussel-Z",
      middel: "Brussel Z./Midi"
    },
    stationType: "MEGA_STATION",
    land: "B",
    UICCode: "8814001",
    lat: 50.8350108,
    lng: 4.3345957,
    radius: 1,
    naderenRadius: 1,
    EVACode: "8800004"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "BSD",
    namen: { lang: "Beesd", kort: "Beesd", middel: "Beesd" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400097",
    lat: 51.8994445800781,
    lng: 5.19444465637207,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400097"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BSK",
    namen: { lang: "Boskoop", kort: "Boskoop", middel: "Boskoop" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400125",
    lat: 52.0777778625488,
    lng: 4.64694452285767,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400125"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BSMZ",
    namen: { lang: "Bussum Zuid", kort: "Bussum Z", middel: "Bussum Z." },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400145",
    lat: 52.2658348083496,
    lng: 5.16305541992188,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400145"
  },
  {
    sporen: [],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BSPD",
    namen: {
      lang: "Berlin-Spandau",
      kort: "Berlin-Spa",
      middel: "Berlin-Spandau"
    },
    stationType: "INTERCITY_STATION",
    land: "D",
    UICCode: "8003025",
    lat: 52.5343152,
    lng: 13.1989467,
    radius: 1,
    naderenRadius: 1,
    EVACode: "8010404"
  },
  {
    sporen: [[Object], [Object], [Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "BTL",
    namen: { lang: "Boxtel", kort: "Boxtel", middel: "Boxtel" },
    stationType: "KNOOPPUNT_STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400129",
    lat: 51.58433,
    lng: 5.31912,
    radius: 260,
    naderenRadius: 800,
    EVACode: "8400129"
  },
  {
    sporen: [],
    synoniemen: ["Bunde"],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BUENDE",
    namen: {
      lang: "Bünde (Westf)",
      kort: "Bünde (W)",
      middel: "Bünde (Westf)"
    },
    stationType: "STOPTREIN_STATION",
    land: "D",
    UICCode: "8021173",
    lat: 52.202075,
    lng: 8.573876,
    radius: 1,
    naderenRadius: 1,
    EVACode: "8000059"
  },
  {
    sporen: [[Object], [Object], [Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "BV",
    namen: { lang: "Beverwijk", kort: "Beverwijk", middel: "Beverwijk" },
    stationType: "INTERCITY_STATION",
    land: "NL",
    UICCode: "8400113",
    lat: 52.4783325195313,
    lng: 4.65666675567627,
    radius: 260,
    naderenRadius: 1200,
    EVACode: "8400113"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "BZL",
    namen: {
      lang: "Kapelle-Biezelinge",
      kort: "Kapelle-Bi",
      middel: "Kapelle-Biezel."
    },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400354",
    lat: 51.4808349609375,
    lng: 3.95611119270325,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400354"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "CAS",
    namen: { lang: "Castricum", kort: "Castricum", middel: "Castricum" },
    stationType: "INTERCITY_STATION",
    land: "NL",
    UICCode: "8400151",
    lat: 52.5458335876465,
    lng: 4.65861129760742,
    radius: 260,
    naderenRadius: 1200,
    EVACode: "8400151"
  },
  {
    sporen: [],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: false,
    code: "CHAMB",
    namen: { lang: "Chambéry", kort: "Chambéry", middel: "Chambéry" },
    stationType: "INTERCITY_STATION",
    land: "F",
    UICCode: "8774100",
    lat: 45.57127,
    lng: 5.91953,
    radius: 1,
    naderenRadius: 1,
    EVACode: "8700055"
  },
  {
    sporen: [[Object], [Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "CK",
    namen: { lang: "Cuijk", kort: "Cuijk", middel: "Cuijk" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400155",
    lat: 51.7266825879048,
    lng: 5.87429523468017,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400155"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "CL",
    namen: { lang: "Culemborg", kort: "Culemborg", middel: "Culemborg" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400154",
    lat: 51.9466667175293,
    lng: 5.22694444656372,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400154"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "CO",
    namen: { lang: "Coevorden", kort: "Coevorden", middel: "Coevorden" },
    stationType: "KNOOPPUNT_SNELTREIN_STATION",
    land: "NL",
    UICCode: "8400153",
    lat: 52.6636123657227,
    lng: 6.73555564880371,
    radius: 525,
    naderenRadius: 1600,
    EVACode: "8400153"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "CPS",
    namen: {
      lang: "Capelle Schollevaar",
      kort: "Schollevr",
      middel: "Schollevaar"
    },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400147",
    lat: 51.9541664123535,
    lng: 4.58416652679443,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400147"
  },
  {
    sporen: [[Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "CVM",
    namen: { lang: "Chevremont", kort: "Chevremont", middel: "Chevremont" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400152",
    lat: 50.8761100769043,
    lng: 6.05972242355347,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400152"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "DA",
    namen: { lang: "Daarlerveen", kort: "Daarlervn", middel: "Daarlerveen" },
    stationType: "STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400164",
    lat: 52.4407702,
    lng: 6.5759947,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400164"
  },
  {
    sporen: [[Object], [Object]],
    synoniemen: [],
    heeftFaciliteiten: true,
    heeftVertrektijden: true,
    heeftReisassistentie: true,
    code: "DB",
    namen: {
      lang: "Driebergen-Zeist",
      kort: "Driebergen",
      middel: "Driebergen-Zeist"
    },
    stationType: "KNOOPPUNT_STOPTREIN_STATION",
    land: "NL",
    UICCode: "8400182",
    lat: 52.0652770996094,
    lng: 5.25861120223999,
    radius: 200,
    naderenRadius: 1200,
    EVACode: "8400182"
  }
];
var departures = [
  {
    links: {},
    payload: {
      source: "PPV",
      departures: [
        {
          direction: "Rhenen",
          name: "NS  7439",
          plannedDateTime: "2019-04-18T11:33:00+0200",
          plannedTimeZoneOffset: 120,
          actualDateTime: "2019-04-18T11:33:00+0200",
          actualTimeZoneOffset: 120,
          plannedTrack: "3",
          product: {
            number: "7439",
            categoryCode: "SPR",
            shortCategoryName: "NS Sprinter",
            longCategoryName: "Sprinter",
            operatorCode: "NS",
            operatorName: "NS",
            type: "TRAIN"
          },
          trainCategory: "SPR",
          cancelled: false,
          routeStations: [
            {
              uicCode: "8400133",
              mediumName: "Breukelen"
            },
            {
              uicCode: "8400621",
              mediumName: "Utrecht C."
            },
            {
              uicCode: "8400182",
              mediumName: "Driebergen-Zeist"
            },
            {
              uicCode: "8400417",
              mediumName: "Maarn"
            }
          ],
          departureStatus: "INCOMING"
        },
        {
          direction: "Rotterdam Centraal",
          name: "NS  4041",
          plannedDateTime: "2019-04-18T11:40:00+0200",
          plannedTimeZoneOffset: 120,
          actualDateTime: "2019-04-18T11:42:45+0200",
          actualTimeZoneOffset: 120,
          plannedTrack: "3",
          product: {
            number: "4041",
            categoryCode: "SPR",
            shortCategoryName: "NS Sprinter",
            longCategoryName: "Sprinter",
            operatorCode: "NS",
            operatorName: "NS",
            type: "TRAIN"
          },
          trainCategory: "SPR",
          cancelled: false,
          routeStations: [
            {
              uicCode: "8400133",
              mediumName: "Breukelen"
            },
            {
              uicCode: "8400702",
              mediumName: "Woerden"
            },
            {
              uicCode: "8400258",
              mediumName: "Gouda"
            }
          ],
          departureStatus: "INCOMING"
        },
        {
          direction: "Uitgeest",
          name: "NS  4034",
          plannedDateTime: "2019-04-18T11:49:00+0200",
          plannedTimeZoneOffset: 120,
          actualDateTime: "2019-04-18T11:49:00+0200",
          actualTimeZoneOffset: 120,
          plannedTrack: "2",
          product: {
            number: "4034",
            categoryCode: "SPR",
            shortCategoryName: "NS Sprinter",
            longCategoryName: "Sprinter",
            operatorCode: "NS",
            operatorName: "NS",
            type: "TRAIN"
          },
          trainCategory: "SPR",
          cancelled: false,
          routeStations: [
            {
              uicCode: "8400074",
              mediumName: "Bijlmer ArenA"
            },
            {
              uicCode: "8400194",
              mediumName: "Duivendrecht"
            },
            {
              uicCode: "8400058",
              mediumName: "Amsterdam C."
            },
            {
              uicCode: "8400059",
              mediumName: "Sloterdijk"
            }
          ],
          departureStatus: "INCOMING"
        },
        {
          direction: "Uitgeest",
          name: "NS  7434",
          plannedDateTime: "2019-04-18T11:58:00+0200",
          plannedTimeZoneOffset: 120,
          actualDateTime: "2019-04-18T11:58:00+0200",
          actualTimeZoneOffset: 120,
          plannedTrack: "2",
          product: {
            number: "7434",
            categoryCode: "SPR",
            shortCategoryName: "NS Sprinter",
            longCategoryName: "Sprinter",
            operatorCode: "NS",
            operatorName: "NS",
            type: "TRAIN"
          },
          trainCategory: "SPR",
          cancelled: false,
          routeStations: [
            {
              uicCode: "8400074",
              mediumName: "Bijlmer ArenA"
            },
            {
              uicCode: "8400194",
              mediumName: "Duivendrecht"
            },
            {
              uicCode: "8400058",
              mediumName: "Amsterdam C."
            },
            {
              uicCode: "8400059",
              mediumName: "Sloterdijk"
            }
          ],
          departureStatus: "INCOMING"
        },
        {
          direction: "Rhenen",
          name: "NS  7441",
          plannedDateTime: "2019-04-18T12:01:00+0200",
          plannedTimeZoneOffset: 120,
          actualDateTime: "2019-04-18T12:01:00+0200",
          actualTimeZoneOffset: 120,
          plannedTrack: "3",
          product: {
            number: "7441",
            categoryCode: "SPR",
            shortCategoryName: "NS Sprinter",
            longCategoryName: "Sprinter",
            operatorCode: "NS",
            operatorName: "NS",
            type: "TRAIN"
          },
          trainCategory: "SPR",
          cancelled: false,
          routeStations: [
            {
              uicCode: "8400133",
              mediumName: "Breukelen"
            },
            {
              uicCode: "8400621",
              mediumName: "Utrecht C."
            },
            {
              uicCode: "8400182",
              mediumName: "Driebergen-Zeist"
            },
            {
              uicCode: "8400417",
              mediumName: "Maarn"
            }
          ],
          departureStatus: "INCOMING"
        },
        {
          direction: "Rotterdam Centraal",
          name: "NS  4043",
          plannedDateTime: "2019-04-18T12:10:00+0200",
          plannedTimeZoneOffset: 120,
          actualDateTime: "2019-04-18T12:10:00+0200",
          actualTimeZoneOffset: 120,
          plannedTrack: "3",
          product: {
            number: "4043",
            categoryCode: "SPR",
            shortCategoryName: "NS Sprinter",
            longCategoryName: "Sprinter",
            operatorCode: "NS",
            operatorName: "NS",
            type: "TRAIN"
          },
          trainCategory: "SPR",
          cancelled: false,
          routeStations: [
            {
              uicCode: "8400133",
              mediumName: "Breukelen"
            },
            {
              uicCode: "8400702",
              mediumName: "Woerden"
            },
            {
              uicCode: "8400258",
              mediumName: "Gouda"
            }
          ],
          departureStatus: "INCOMING"
        },
        {
          direction: "Uitgeest",
          name: "NS  4036",
          plannedDateTime: "2019-04-18T12:19:00+0200",
          plannedTimeZoneOffset: 120,
          actualDateTime: "2019-04-18T12:19:00+0200",
          actualTimeZoneOffset: 120,
          plannedTrack: "2",
          product: {
            number: "4036",
            categoryCode: "SPR",
            shortCategoryName: "NS Sprinter",
            longCategoryName: "Sprinter",
            operatorCode: "NS",
            operatorName: "NS",
            type: "TRAIN"
          },
          trainCategory: "SPR",
          cancelled: false,
          routeStations: [
            {
              uicCode: "8400074",
              mediumName: "Bijlmer ArenA"
            },
            {
              uicCode: "8400194",
              mediumName: "Duivendrecht"
            },
            {
              uicCode: "8400058",
              mediumName: "Amsterdam C."
            },
            {
              uicCode: "8400059",
              mediumName: "Sloterdijk"
            }
          ],
          departureStatus: "INCOMING"
        },
        {
          direction: "Uitgeest",
          name: "NS  7436",
          plannedDateTime: "2019-04-18T12:28:00+0200",
          plannedTimeZoneOffset: 120,
          actualDateTime: "2019-04-18T12:28:00+0200",
          actualTimeZoneOffset: 120,
          plannedTrack: "2",
          product: {
            number: "7436",
            categoryCode: "SPR",
            shortCategoryName: "NS Sprinter",
            longCategoryName: "Sprinter",
            operatorCode: "NS",
            operatorName: "NS",
            type: "TRAIN"
          },
          trainCategory: "SPR",
          cancelled: false,
          routeStations: [
            {
              uicCode: "8400074",
              mediumName: "Bijlmer ArenA"
            },
            {
              uicCode: "8400194",
              mediumName: "Duivendrecht"
            },
            {
              uicCode: "8400058",
              mediumName: "Amsterdam C."
            },
            {
              uicCode: "8400059",
              mediumName: "Sloterdijk"
            }
          ],
          departureStatus: "INCOMING"
        },
        {
          direction: "Rhenen",
          name: "NS  7443",
          plannedDateTime: "2019-04-18T12:33:00+0200",
          plannedTimeZoneOffset: 120,
          actualDateTime: "2019-04-18T12:33:00+0200",
          actualTimeZoneOffset: 120,
          plannedTrack: "3",
          product: {
            number: "7443",
            categoryCode: "SPR",
            shortCategoryName: "NS Sprinter",
            longCategoryName: "Sprinter",
            operatorCode: "NS",
            operatorName: "NS",
            type: "TRAIN"
          },
          trainCategory: "SPR",
          cancelled: false,
          routeStations: [
            {
              uicCode: "8400133",
              mediumName: "Breukelen"
            },
            {
              uicCode: "8400621",
              mediumName: "Utrecht C."
            },
            {
              uicCode: "8400182",
              mediumName: "Driebergen-Zeist"
            },
            {
              uicCode: "8400417",
              mediumName: "Maarn"
            }
          ],
          departureStatus: "INCOMING"
        }
      ]
    },
    meta: {}
  }
];
